### ISSUE TITLE
Public scripts and CSS are being enqueued with no content

### ISSUE THREAD

**Issue by andrewlreeve** [dotmailer/dotdigital-for-woocommerce#14]
By default, the boilerplate template used for this plugin enqueues a public stylesheet and script file. 

As there is no content in those files and they are not required, they can be safely dequeued to reduce requests and script loads on client sites.

**Comment by sta1r** [comment]
Hi @andrewlreeve - we've got a fix for this one, which is now on our develop branch. We'll release to master probably within the next month, I'll confirm.
